JustReactJS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JustReactJS.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

JustReactJS/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JustReactJS.Controllers
{
	public class TestController : Controller
	{
		// GET: Test
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult HelloWorld()
		{
			return View();
		}
		public ActionResult HelloWorldServerSide()
		{
			return View();
		}

		public ActionResult TextField()
		{
			return View();
		}
	}
}

JustReactJS/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<ul>
	<li><a href="@Url.Action("HelloWorld","Test")">Hello World</a></li>
	<li><a href="@Url.Action("TestField","Test")">Test Field</a></li>
	<li><a href="@Url.Action("HelloWorldServerSide","Test")">Hello World Server Side</a></li>
</ul>

JustReactJS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>React Js Tests</title>
	<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
	<script src="~/Scripts/libs/react.js"></script>
	<script src="~/Scripts/libs/react-dom.js"></script>
</head>
<body>
	<div class="content" >
		@RenderBody()
	</div>
	<div class="footer">
		<a href="@Url.Action("Index","Home")">Home</a>
	</div>
</body>
</html>

JustReactJS/Views/Test/HelloWorld.cshtml
@{
    ViewBag.Title = "HelloWorld";
}

<h2>HelloWorld</h2>

<div id="container"></div>

<script src="@Url.Content("~/Scripts/JSX/HelloWorld.jsx")"></script>

JustReactJS/Views/Test/HelloWorldServerSide.cshtml
@{
    ViewBag.Title = "HelloWorld server side";
}

<h2>HelloWorld server side</h2>

<script>
	debugger;
	$(document).ready(function () { debugger; });
</script>

<div id="container"></div>
@Html.React("HelloWorldComponent", new
{
	greetTarget = "Gym"
})

<script src="@Url.Content("~/Scripts/JSX/HelloWorldComponent.jsx")"></script>
<script src="@Url.Content("~/Scripts/JSX/HelloWorldServerSide.jsx")"></script>
@Html.ReactInitJavaScript()

JustReactJS/Views/Test/TextField.cshtml
@{
    ViewBag.Title = "TextField";
}

<h2>Text Field</h2>

<div id="container"></div>

<script src="@Url.Content("~/Scripts/JSX/TextField.jsx")"></script>